### ISSUE TITLE
Broken Python 3.8 Support

### ISSUE THREAD

**Issue by Frustrated-Programmer9001** [rany2/edge-tts#96]
I'm trying to run the basic_generation example but I'm getting errors:

![image](https://github.com/rany2/edge-tts/assets/135358649/9b342c02-d5f3-4f4b-ac5c-f92f1dba3ceb)

**Comment by rany2** [comment]
Fixed in 6.1.6:  https://github.com/rany2/edge-tts/commit/ca6e7b06691f3bb9c8892c630fd648abd987957b

**Comment by Frustrated-Programmer9001** [comment]
I've tried the new version and I'm still getting the same errors.
![image](https://github.com/rany2/edge-tts/assets/135358649/e07e4e24-05eb-4ab1-8564-1e2ba2188053)

**Comment by rany2** [comment]
Which python version?

**Comment by Frustrated-Programmer9001** [comment]
3.8.16
